server:
  port: 80
  servlet:
    context-path: /shop

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  thymeleaf:
    cache: true